# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qttas-server

# >> macros
# << macros

Summary:    Qt Test Automation Server
Version:    1.5.4
Release:    1
Group:      Development/Tools
License:    LGPL
URL:        https://github.com/d0b3rm4n/agent_qt
Source0:    tdriver-agent_qt-1.5.4.tar.gz
Source1:    qttas-ui.desktop
Source100:  qttas-server.yaml
Requires:   qttas-server-plugins
Requires:   qttas-server-libs
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xtst)
BuildRequires:  desktop-file-utils

%description
Qt TAS is a test automation server which provides testability 
interface. Interface is used to access UI components to 
verify and control them.


%package libs
Summary:    Qt Test automation server library files
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
Qt TAS development library files

%package plugins
Summary:    Qt Test automation server plugins
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description plugins
Qt Test Automation Server plugins

%package devel
Summary:    Qt Test automation server development headers
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires:   qttas-server-libs

%description devel
Qt TAS development header.


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
qmake -r CONFIG+=RPM CONFIG+=no_mobility CONFIG+=qml_id
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre

# << install pre
%make_install

# >> install post
install -D -m 644 %{SOURCE1} %{buildroot}%{_datadir}/applications/qttas-ui.desktop
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/qttas*
%config %{_sysconfdir}/qt_testability/*
%config %{_sysconfdir}/xdg/autostart/qttasserver.desktop
%{_datadir}/applications/qttas-ui.desktop
%dir  %{_sysconfdir}/qt_testability
# << files

%files libs
%defattr(-,root,root,-)
# >> files libs
%{_libdir}/lib*.so.*
%{_libdir}/lib*.so
# << files libs

%files plugins
%defattr(-,root,root,-)
# >> files plugins
%{_libdir}/qt4/plugins/*
# << files plugins

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/tdriver/*
%{_datadir}/qt4/mkspecs/features/*
%{_datadir}/doc/qttas-dev/examples
%dir %{_includedir}/tdriver
%dir %{_datadir}/doc/qttas-dev
# << files devel
